### ISSUE TITLE
OpenVINO model server example fails...

### ISSUE THREAD

**Issue by bhargav-sudo** [openvinotoolkit/model_server#441] opened 2020-12-28 07:50 UTC
Hiii , 

I am currently working on this in ubuntu 18.04  machine [https://github.com/openvinotoolkit/model_server/blob/main/docs/face_detection_script_example.md](url) 

My models were placed at models/model1/1/facedetection.xml

I can able to start the docker using this command : - 

**docker run -d -v $(pwd)/model:/models -p 9000:9000 openvino/model_server:latest  --model_path /models/model1/1 --model_name face-detection --port 9000  --shape auto**
I don't know whether this command is correct or not .. If any changes need to made in previous command. Let me know

But when Iam running the **face_detection.py** file
It shows the error like this 

2020-12-28 13:17:59.263573: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2020-12-28 13:17:59.263595: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
['people1.jpeg', 'people2.jpeg', 'people3.jpeg', 'people4.jpeg']
Start processing 4 iterations with batch size 1

Request shape (1, 3, 300, 300)
Traceback (most recent call last):
  File "face_detection.py", line 94, in <module>
    result = stub.Predict(request, 10.0) # result includes a dictionary with all model outputs
  File "/my_tensorflow/venv/lib/python3.6/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/my_tensorflow/venv/lib/python3.6/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1609141680.374217669","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4133,"referenced_errors":[{"created":"@1609141680.374209599","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"

please help me to work on this issue
Thanks in advance...

**Comment by dtrawins** [comment] 2020-12-29 23:59
@bhargav-sudo `--model_path` parameter should point to the model folder with model versions included. You should change it to  `/models/model1`.
Client error indicates that it can't connect to the endpoint. Probably because OVMS was not started with incorrect model path. It could be also confirmed in the ovms container logs.

**Comment by bhargav-sudo** [comment] 2020-12-31 07:01
@dtrawins will try that and let you know
Thanks

**Comment by bhargav-sudo** [comment] 2020-12-31 08:01
Hi @dtrawins 

I worked on this link [https://github.com/openvinotoolkit/model_server/blob/main/docs/ovms_quickstart.md](url)
I completed all the steps 

When Iam running the **face_detection**.py file

The command I used **: python face_detection.py --batch_size 1 --width 600 --height 400 --input_images_dir images --output_dir results**


It shows this error

2020-12-31 13:18:08.217566: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-12-31 13:18:08.217591: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Running face-detection on files:['airliner.jpeg', 'arctic-fox.jpeg', 'bee.jpeg', 'golden_retriever.jpeg', 'gorilla.jpeg', 'magnetic_compass.jpeg', 'peacock.jpeg', 'pelican.jpeg', 'people', 'snail.jpeg', 'zebra.jpeg', 'people1.jpeg', 'people2.jpeg']
Traceback (most recent call last):
  File "face_detection.py", line 62, in <module>
    img = load_image(os.path.join(args['input_images_dir'], i))
  File "face_detection.py", line 31, in load_image
    img = cv2.resize(img, (args['width'], args['height']))
cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/resize.cpp:3720: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by Mohamad1994HD** [comment] 2021-01-04 20:21
Yes the solution @dtrawins mentioned worked for me as well, at the beginning, it could be tricky what is what. Then I came through their guideline:

[https://github.com/openvinotoolkit/model_server/blob/main/docs/models_repository.md](https://github.com/openvinotoolkit/model_server/blob/main/docs/models_repository.md
)

**Comment by bhargav-sudo** [comment] 2021-01-06 03:36
@dtrawins and @Mohamad1994HD Thanks for your assistance..
It Works fine now..

@dtrawins It's very good If you make any video to understand the workflow of **OVMS** in detailed..

Thanks..

**Comment by bhargav-sudo** [comment] 2021-01-06 16:17
@dtrawins I got the video..
It's a webinar recording ..

Thanks...

**Comment by bhargav-sudo** [comment] 2021-01-07 06:09
@dtrawins and @Mohamad1994HD this is my command to start the docker 

**docker run -d -v $(pwd)/model:/models/model1 -p 9000:9000 openvino/model_server:latest  --model_path /models/model1 --model_name face-detection --port 9000  --shape auto**

My docker exits immediately after execution..

So, I am not able to run client application..
It shows the same error..

**Comment by Mohamad1994HD** [comment] 2021-01-07 16:08
remove the -d to see the error logs,

you may mount the models directly
```
  -v $(pwd)/model:/models
 --model_path    |/models/model1
```

so what appears inside the docker is /models/model1/1/
and use the model path as  --model_path /models/model1/
so it finds the model versions under the path

But if you mount the model directory as
```
-v $(pwd)/model:/models/model1 then did

--model_path                 |/models/model1
```
The model wouldn't be found ( starting from the | )

I believe the --model_name is just for registering a name to interact with it via a client not for reaching the model file.

This what I found from experimenting with it, please correct me if I got it wrong

**Comment by bhargav-sudo** [comment] 2021-01-07 16:13
@Mohamad1994HD will try and let you know that..
Thanks.

**Comment by bhargav-sudo** [comment] 2021-01-07 16:18
@Mohamad1994HD I removed option -d from the command 

 **docker run -v $(pwd)/model:/models/model1 -p 9000:9000 openvino/model_server:latest --model_path /models/model1 --model_name face-detection --port 9000 --shape auto**

[2021-01-07 16:17:46.285][modelmanager][error][modelmanager.cpp:586] Couldn't list directories in path: /models/model1
[2021-01-07 16:17:46.285][modelmanager][error][modelmanager.cpp:60] Couldn't start model manager
[2021-01-07 16:17:46.285][serving][error][server.cpp:175] ovms::ModelManager::Start() Error: The provided base path is invalid or doesn't exists

It shows this 
what I had to do now..?

let me know ASAP....
Thanks.

**Comment by bhargav-sudo** [comment] 2021-01-10 15:34
Hi @Mohamad1994HD and @dtrawins ...
Any updates on this above error

My models were placed in that position..
Let me know how to resolve the error as soon as possible..

Thanks..

**Comment by Mohamad1994HD** [comment] 2021-01-10 15:41
`docker run -v $(pwd)/model:/models/ -p 9000:9000 openvino/model_server:latest --model_path /models/model1 --model_name face-detection --port 9000 --shape auto`

```
models/
    model1/
       1/
          xml, bin
    model2/
       1/
          xml, bin
    .
    .
```

Please double check the first link I mentioned in this thread. And just mount the root of the models not the insiders,
while in the --model_path you give the folder name of the model
It should work

**Comment by bhargav-sudo** [comment] 2021-01-10 15:42
Thanks @Mohamad1994HD 

Will let you know..

**Comment by bhargav-sudo** [comment] 2021-01-10 15:53
Hi @Mohamad1994HD 


my models were place like you said ...
I used this command ..

**docker run -v $(pwd)/model:/models/ -p 9000:9000 openvino/model_server:latest --model_path /models/model1 --model_name face-detection --port 9000 --shape auto**

It is showing same error 
I don't know why.?

can you help me in the steps using this link..

[https://github.com/openvinotoolkit/model_server/blob/main/docs/face_detection_script_example.md](url)

**Comment by Mohamad1994HD** [comment] 2021-01-10 16:07
I have reproduced your issue and found that the example that worked included user forwarding to the docker `-u $(id -u):$(id -g)` in the command docker run.

To be honest I have no idea why forwarding the host machine user is required! I am using the 2021.2 version.  Let us wait to check what are the maintainer's thoughts

**Comment by bhargav-sudo** [comment] 2021-01-10 16:12
Thanks @Mohamad1994HD 
for your assistance..

@dtrawins please let us know as soon as possible...
Thanks .

**Comment by bhargav-sudo** [comment] 2021-01-10 16:19
@Mohamad1994HD is there any place that should I put that **models** folder ...?

**Comment by dtrawins** [comment] 2021-01-11 11:20
@bhargav-sudo @Mohamad1994HD  Docker parameters `-u $(id -u):$(id -g)` ensure the OVMS security context is identical with the account downloading the models. With difference security context, mounted models with permissions mask `700` could be not accessible by ovms process. Alternatively you could also change model permissions to `755` or start the docker container with root security contect `-u root`.
Models should be accessible from the docker container. Any location on the host is fine as long it is mounted in the container. Note that that visible in the container might be different from the host path depending on the mounting parameters in docker command `-v host_path:container_path`. ovms process (running in defined security context) in the container need `read` permissions to the model files and `list/execute` permissions on the folders with model files.

**Comment by bhargav-sudo** [comment] 2021-01-12 09:29
@dtrawins sorry to Interrupt ..

I changed permission of models (xml and bin) to 755

-rwxrwxrwx  face-detection-retail-0004.bin
-rwxrwxrwx  face-detection-retail-0004.xml

and gave 777 permission to the folders with model files.

 It is showing the error..

Command  : 

 **docker run -v $(pwd)/model:/models/ -p 9000:9000 openvino/model_server:latest --model_path /models/model1 --model_name face-detection --port 9000 --shape auto**

**[2021-01-12 09:27:44.771][modelmanager][error][modelmanager.cpp:575] Couldn't check directory: /models/model1
[2021-01-12 09:27:44.771][modelmanager][error][modelmanager.cpp:60] Couldn't start model manager
[2021-01-12 09:27:44.771][serving][error][server.cpp:175] ovms::ModelManager::Start() Error: The provided base path is invalid or doesn't exists**

@dtrawins By default docker runs as root right..?

Thanks

**Comment by dtrawins** [comment] 2021-01-13 16:41
@bhargav-sudo Assuming your model is stored in $(pwd)/model and it has a subfolder `1` with model files `.xml` and `.bin`, the command should be updated:
`docker run -v $(pwd)/model:/models/model1 -p 9000:9000 openvino/model_server:latest --model_path /models/model1 --model_name face-detection --port 9000 --shape auto`
By default, ovms is started in a security context of `ovms` account with pid 5000.

**Comment by bhargav-sudo** [comment] 2021-01-14 03:14
Hi @dtrawins I tried like you said ..

And gave permission to the  $(pwd)/model and subfolder 1
gave permission for .xml and .bin too..

It shows error again : 
command : 

**docker run -v $(pwd)/model:/models/model1 -p 9000:9000 openvino/model_server:latest --model_path /models/model1 --model_name face-detection --port 9000 --shape auto**

[2021-01-14 03:11:55.402][modelmanager][warning][modelmanager.cpp:607] No version found for model in path: /models/model1
[2021-01-14 03:11:55.402][modelmanager][error][modelmanager.cpp:60] Couldn't start model manager
[2021-01-14 03:11:55.402][serving][error][server.cpp:175] ovms::ModelManager::Start() Error: Not a single model version directory has valid numeric name

Thanks.

**Comment by dtrawins** [comment] 2021-01-14 10:09
@bhargav-sudo The model path defined by `--model_path` should include numerical subfolders representing the versions of the model.
For example like here:
```
models/
├── model1
│   ├── 1
│   │   ├── ir_model.bin
│   │   └── ir_model.xml
│   └── 2
│       ├── ir_model.bin
│       └── ir_model.xml
```
In your case make sure the folder `$(pwd)/model` includes the subfolder `1` with the model files.
Alternatively you can change the docker mounting params to `-v $(pwd)/model:/models/model1/1`. All in all, inside the docker container, the model path must include versions of the model (at least one version) with the model files.

**Comment by bhargav-sudo** [comment] 2021-01-14 10:20
@dtrawins 


Finally it works for me 


Using this command 

**docker run -v $(pwd)/model:/models/model1/1 -p 9000:9000 openvino/model_server:latest --model_path /models/model1/1 --model_name face-detection --port 9000 --shape auto**

My model structure

**models
├── model1
│   ├── 1
│   │   ├── face-detection-retail-0004.bin
│   │   └── face-detection-retail-0004.xml
│   └── 2
│       ├── person-vehicle-bike-detection-crossroad-0078.bin
│       └── person-vehicle-bike-detection-crossroad-0078.xml
└── model2
    └── 1
        ├── person-vehicle-bike-detection-crossroad-0078.bin
        └── person-vehicle-bike-detection-crossroad-0078.xml**


Thanks

**Comment by bhargav-sudo** [comment] 2021-01-14 10:21
Thanks @dtrawins and @Mohamad1994HD  for the assistance...

**Comment by dtrawins** [comment] 2021-01-15 15:49
@bhargav-sudo with your folder structure I would use the command below:
```docker run -v $(pwd)/models:/models/ -p 9000:9000 openvino/model_server:latest --model_path /models/model1/ --model_name face-detection --port 9000 --shape auto```
Anyway I'm glad it is working for you and I'm closing this issue.

**Closed by dtrawins** 2021-01-15 15:49 UTC
Labels: help wanted

**Comment by bhargav-sudo** [comment] 2021-01-16 04:09
@dtrawins by using above command tooo..

It works fine
Thanks..
